name: sd-mac-build

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: macos-14

    steps:
      # ① Клонируем репозиторий вместе с подмодулями
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 1

      # ② Конфигурация CMake (универсальный статический билд с Metal)
      - name: Configure
        run: |
          cmake -B build \
                -DCMAKE_BUILD_TYPE=Release \
                -DSD_METAL=ON \
                -DBUILD_SHARED_LIBS=OFF \
                -DCMAKE_OSX_ARCHITECTURES="x86_64;arm64"

      # ③ Сборка sd и sd-server
      - name: Build
        run: |
          cmake --build build --config Release -j$(sysctl -n hw.logicalcpu)
          cmake --build build --config Release --target sd-server -j$(sysctl -n hw.logicalcpu)

      # ④ Артефакты (оба бинаря)
      - uses: actions/upload-artifact@v4
        with:
          name: sd-mac-universal
          path: |
            build/bin/sd
            build/bin/sd-server
            build/bin/libstable-diffusion*.dylib
            build/bin/*.metal
            build/bin/ggml-*.h
